# Generated by Django 2.2.3 on 2019-07-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreage', models.PositiveSmallIntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Farm')),
            ],
        ),
    ]
