# Generated by Django 2.2.3 on 2019-07-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
