# Generated by Django 2.2.4 on 2019-09-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='max_expense',
            field=models.FloatField(default=0.0),
        ),
    ]
