# Generated by Django 2.2.4 on 2019-10-05 12:27

from django.db import migrations, models


def setNote(apps, schema_editor):
    '''set the note for 1000 acre farms'''
    Farm = apps.get_model('farm', 'Farm')
    for farm in Farm.objects.all():
        farm.note = "This farm has ten 100-acre fields, "\
                    "It is an example farm for evaluating the tool."
        farm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farm_max_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(setNote, migrations.RunPython.noop),
    ]
