# Generated by Django 2.2.4 on 2019-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20190719_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=32)),
                ('prices', models.CharField(default='', max_length=4096)),
                ('yields', models.CharField(default='', max_length=4096)),
                ('cost', models.FloatField(default=0.0)),
                ('price_stats', models.CharField(default='', max_length=2048)),
                ('yield_stats', models.CharField(default='', max_length=2048)),
                ('price_histo', models.CharField(default='', max_length=2048)),
                ('yield_histo', models.CharField(default='', max_length=2048)),
            ],
        ),
    ]
