# Generated by Django 2.2.3 on 2019-07-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('acres', models.PositiveSmallIntegerField()),
                ('the_nets', models.CharField(max_length=2048)),
                ('mean', models.FloatField()),
                ('the_box', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_yields', models.CharField(max_length=1024)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=32)),
                ('the_nets', models.CharField(max_length=2048)),
                ('the_histogram', models.CharField(max_length=2048)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_prices', models.CharField(max_length=1024)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.Crop')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.Scenario'),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.Crop')),
            ],
        ),
    ]
