# Generated by Django 2.2.4 on 2019-08-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropdata',
            options={'verbose_name_plural': 'cropdata'},
        ),
        migrations.AddField(
            model_name='priceoverride',
            name='factor',
            field=models.FloatField(default=1.0),
        ),
    ]
