# Generated by Django 2.2.4 on 2019-08-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_auto_20190809_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceoverride',
            name='safety',
            field=models.CharField(default='median', max_length=6),
        ),
    ]
