# Generated by Django 2.2.3 on 2019-07-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_auto_20190715_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='histogram',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='quartiles',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='std',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='the_prices',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='the_yields',
        ),
    ]
