# Generated by Django 2.2.4 on 2019-09-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_priceoverride_safety'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceOverride',
            new_name='PriceOrder',
        ),
        migrations.RenameField(
            model_name='cropdata',
            old_name='prices',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cropdata',
            old_name='yields',
            new_name='yld',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='mean',
            new_name='hi',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='q1',
            new_name='lo',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='q3',
            new_name='peak',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='price_histo',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='price_stats',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='yield_histo',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='yield_stats',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='mean_partition',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='q1_partition',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='q3_partition',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='state',
        ),
        migrations.AddField(
            model_name='crop',
            name='price_override',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='price_override',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='crop',
            name='yield_override',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='yield_override',
            field=models.CharField(default='', max_length=128),
        ),
    ]
