# Generated by Django 2.2.4 on 2019-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_auto_20190923_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='expected',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='expected_partition',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='scenario',
            name='max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='max_partition',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='scenario',
            name='min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='min_partition',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
