# Generated by Django 2.2.4 on 2019-09-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0005_auto_20190924_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropdata',
            old_name='price',
            new_name='prices',
        ),
        migrations.RenameField(
            model_name='cropdata',
            old_name='yld',
            new_name='yields',
        ),
    ]
