# Generated by Django 2.2.4 on 2019-09-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0006_auto_20190924_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='expected',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='expected_partition',
        ),
        migrations.AddField(
            model_name='crop',
            name='farmcrop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='optimizer.FarmCrop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='peak_partition',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='max',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='max_partition',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='min',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='min_partition',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='peak',
            field=models.CharField(default='', max_length=512),
        ),
    ]
