# Generated by Django 2.2.4 on 2019-09-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0007_auto_20190924_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='max',
            new_name='max_triangle',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='peak_partition',
            new_name='mean_partition',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='min',
            new_name='min_triangle',
        ),
        migrations.AddField(
            model_name='scenario',
            name='mean_triangle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='peak',
            field=models.FloatField(default=0.0),
        ),
    ]
