# Generated by Django 2.2.4 on 2019-09-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0008_auto_20190930_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='hi',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='lo',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='peak',
        ),
    ]
