# Generated by Django 2.2.4 on 2019-09-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0009_auto_20190930_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='max_expense',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='mean_expense',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='min_expense',
            field=models.FloatField(default=0.0),
        ),
    ]
