# Generated by Django 2.2.4 on 2019-10-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0010_auto_20190930_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceorder',
            name='safety',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
