# Generated by Django 2.2.4 on 2019-10-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0011_auto_20191001_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='yield_override',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='yield_override',
            field=models.FloatField(default=1.0),
        ),
    ]
