# Generated by Django 2.2.4 on 2019-10-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0012_auto_20191001_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='yield_override',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='yield_override',
            field=models.CharField(default='', max_length=128),
        ),
    ]
