# Generated by Django 2.2.4 on 2019-11-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0013_auto_20191001_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceorder',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_orders', to='optimizer.Crop'),
        ),
    ]
