# Generated by Django 2.2.4 on 2019-11-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0015_remove_priceorder_safety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceorder',
            name='factor',
        ),
        migrations.AddField(
            model_name='priceorder',
            name='safety',
            field=models.CharField(default='Medium', max_length=10),
            preserve_default=False,
        ),
    ]
