# Generated by Django 3.1.2 on 2020-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('crop', models.CharField(choices=[('C', 'corn'), ('W', 'wheat'), ('S', 'soybeans')], max_length=1)),
                ('open', models.DecimalField(decimal_places=2, max_digits=5)),
                ('close', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='kind',
            field=models.CharField(choices=[('E', 'elevator'), ('M', 'feed mill'), ('S', 'soybeans processor')], max_length=1),
        ),
    ]
