# Generated by Django 3.1.2 on 2020-12-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge', '0002_auto_20201214_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='future',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('date',)},
        ),
    ]
